### ISSUE TITLE
How to train ATRank with different types behaviours?

### ISSUE THREAD

**Issue by xiaochenwang94** [jinze1994/ATRank#10]
In multi/model.py, it seems we can only use one type behavior train the model. But in your paper, you concat different type of feature from different bg. How can I use different type behaviors at the same time?

**Comment by jinze1994** [comment]
The code from [Line31](https://github.com/jinze1994/ATRank/blob/2031fd112c0bf5c84beba284492bc4c7dcf476e7/multi/model.py#L40) to [Line70](https://github.com/jinze1994/ATRank/blob/2031fd112c0bf5c84beba284492bc4c7dcf476e7/multi/model.py#L70) provides an example of the different behaviors and heterogeneous features from multiple sources, where the item, query, and coupon denote three different behaviors.

**Comment by xiaochenwang94** [comment]
But in train function at line 298https://github.com/jinze1994/ATRank/blob/2031fd112c0bf5c84beba284492bc4c7dcf476e7/multi/model.py#L298, each time you only feed one type behavior in your model.

**Comment by jinze1994** [comment]
For the user history part, You could feed multiple types of behaviors, including item history, query history, and coupon history. 

For the target of prediction, you can only feed one type of behavior in a single batch and feed different types in turn in different batches.

**Comment by xiaochenwang94** [comment]
Thank you very much
