### ISSUE TITLE
High cpu usage when running the code

### ISSUE THREAD

**Issue by liyongqi67** [jinze1994/ATRank#5]
I run the atrank network on my own dataset. I use the top command and find that the code consumes high cpu usage(1500%). I'm sure the network causes that because if I remove the network, it's normal.And I'm sure the network is running on Gpu. And if i use "session_conf = tf.ConfigProto( intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)" to  limit the number of CPUs that tensorflow can use, the usage of cpu will not be high but the speed is very slow .So is there some ops in atrank consuming cpu? When you run the code, is there a high cpu usage?

**Comment by jinze1994** [comment]
Thanks for your attention to our work. I didn't observe the CPU problem in our experiments. The placements of OP are made by tensorflow, and you can change it manually by `tf.device("/device:GPU:0")`. As far as we know all ops we use have both the CPU and GPU implement. Furthermore, you can print the tensor or watch them in tensorboard, which you can figure out where the ops are placed.

**Comment by liyongqi67** [comment]
Thanks for your reply! I will check my code! Maybe there is something that I didn't notice.

**Comment by liyongqi67** [comment]
Hi! I have solved the problem. The thing is that the op 'tf.tile()' in tensorflow1.4 is running on cpus even with the tensorflow of gpu version . Fortunately, the problem have been fixed in the new tf version.
