### ISSUE TITLE
What is the shape of hist_i_emb?

### ISSUE THREAD

**Issue by xiaochenwang94** [jinze1994/ATRank#9]
https://github.com/jinze1994/ATRank/blob/2031fd112c0bf5c84beba284492bc4c7dcf476e7/multi/model.py#L146

This line input is hist_i_emb, which length is various from different data. You input this tensor into a Dense layer. The Dense layer need a fix-length input. I don't understand here.

**Comment by jinze1994** [comment]
The shape of `hist_i_emb` is `[B, T, H]`, where `B` is the batch size, `T` is the size of the maximum time step, and `H` is the hidden size. The second dimension is aligned to `T` and there is another tensor `hist_i_sl` denoting the sequence length of `hist_i_emb`. The process of aligning is in the file `input.py`.
